# Generated by Django 3.2.7 on 2021-09-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
